---
- name: Build a Alpine Linux docker image with nginx
  hosts: bp
  become: true

  tasks:

    - name: copy the Dockerfile and ngnix config files to remote host
      copy:
        src: ./bp-site
        dest: /tmp/
        mode: 0755


    # - name: Build the Alpine Linux docker image with nginx
    #  docker_image:
    #    path: /tmp/bp-site
    #    name: somename
    #    tag: v1
    #    state: present
    # THIS FAILS with:
    #
    # TASK [Build the Alpine Linux docker image with nginx] **************************
    # fatal: [bp-test]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"}
    #
    # Lots of bugs are reported.

    - name: Build the Alpine Linux docker image with nginx using the command module
      command: docker build -t virantha-alpine-nginx /tmp/bp-site

    - name: do some cleanup. delete /tmp/bp-site
      file:
        state: absent
        path: "/tmp/bp-site"
